setup:
  project: depth

data:
  resize_size: 224
  crop_size: 224
  no_vflip: False
  rotate_angle: 180
  color_augment: True

optim:
  lr: 0.00035
  weight_decay: 0.1

model:
  min_depth: 0.001
  max_depth: 10
  n_bins: 80
  norm: 'linear'
  feature_extraction_layer: 'encoder0'
  softmax_first: True

scheduler:
  lr: 0.0001
  div_factor: 25
  final_div_factor: 100

train:
  batch_size: 6
  epochs: 10
  w_chamfer: 0.1
  sample_every: 20
  save_every: 6000
